// Данные карточек (продукты)
export const initialProducts = [
  {
    id: '0',
    name: ' блинчики с мясом',
    category: 'Stock',
    description: 'Г/Ц Блинчики с мясом вес, Россия',
    rating: '2.0',
    card: '44,50',
    regular: '50.50',
    imgSrc: '../assets/products/блинчики с мясом.svg',
    isFavorite: true,
    cartQuantity: 1,
  },
  {
    id: '1',
    name: 'молоко простоквашино',
    category: 'Stock',
    description: 'Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...',
    rating: '3.0',
    card: '44,50',
    regular: '50.50',
    imgSrc: '../assets/products/молоко ПРОСТОКВАШИНО.svg',
    isFavorite: true,
    cartQuantity: 1,
  },
  {
    id: '2',
    name: 'колбаса сырокопченая',
    category: 'Stock',
    description: 'Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...',
    rating: '5.0',
    card: '44,50',
    regular: '50.50',
    imgSrc: '../assets/products/колбаса сырокопченая.svg',
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: '3',
    name: 'сосиски вареные',
    category: 'Stock',
    description: 'Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...',
    rating: '4.5',
    card: '44,50',
    regular: '50.50',
    imgSrc: '../assets/products/сосиски вареные.svg',
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: '4',
    name: 'колбаса Черкизово премиум',
    category: 'New items',
    description: 'Колбаса сырокопченая, Черкизово премиум',
    rating: '2.0',
    price: '599.99',
    imgSrc: '../assets/products/колбаса черкизово премиум.svg',
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: '5',
    name: 'колбаса сырокопченая',
    category: 'New items',
    description: 'Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...',
    rating: '5.0',
    price: '50.50',
    imgSrc: '../assets/products/колбаса сырокопченая.svg',
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: '6',
    name: 'сосиски вареные',
    category: 'New items',
    description: 'Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...',
    rating: '4.0',
    price: '159.99',
    imgSrc: '../assets/products/сосиски вареные.svg',
    isFavorite: true,
    cartQuantity: 1,
  },
  {
    id: '7',
    name: 'молоко простоквашино',
    category: 'New items',
    description: 'Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...',
    rating: '3.0',
    price: '50.50',
    imgSrc: '../assets/products/молоко ПРОСТОКВАШИНО.svg',
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: '8',
    name: 'ветчина питерская',
    category: 'Purchased before',
    description: 'Ветчина Питерская,  ОТБОРНЫЕ ПРОДУКТЫ',
    rating: '2.0',
    price: '77.99',
    imgSrc: '../assets/products/ветчина питерская.svg',
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: '9',
    name: 'сосиски вареные',
    category: 'Purchased before',
    description: 'Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...',
    rating: '4.0',
    price: '159.99',
    imgSrc: '../assets/products/сосиски вареные.svg',
    isFavorite: true,
    cartQuantity: 1,
  },
  {
    id: '10',
    name: 'колбаса Черкизово премиум',
    category: 'Purchased before',
    description: 'Колбаса сырокопченая, Черкизово премиум',
    rating: '2.0',
    price: '599.99',
    imgSrc: '../assets/products/колбаса черкизово премиум.svg',
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: '11',
    name: 'молоко простоквашино',
    category: 'Purchased before',
    description: 'Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...',
    rating: '3.0',
    price: '50.50',
    imgSrc: '../assets/products/молоко ПРОСТОКВАШИНО.svg',
    isFavorite: true,
    cartQuantity: 1,
  },
]
